//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTUpdatePortalApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LTUpdatesEntities : DbContext
    {
        public LTUpdatesEntities()
            : base("name=LTUpdatesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Flash_Updates> Flash_Updates { get; set; }
        public virtual DbSet<LT_Updates> LT_Updates { get; set; }
        public virtual DbSet<PDRM_Updates> PDRM_Updates { get; set; }
        public virtual DbSet<Update> Updates { get; set; }
        public virtual DbSet<PortalUpdate> PortalUpdates { get; set; }
    }
}
